//! Orchestration flow integration tests: event ordering, state machine
//! traversal, role boundaries, and end-to-end verdicts over fixtures.
// Test code may panic on assertion failure.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use supplyguard::audit::AuditChain;
use supplyguard::mcp::{NpmLocal, OsvLocal, SpdxLocal};
use supplyguard::models::ids::SessionId;
use supplyguard::models::messages::{DependencyChange, EventSource, RiskLevel, Verdict};
use supplyguard::models::session::SessionState;
use supplyguard::runtime::orchestrator::{LocalOrchestrator, OrchestratorEvent, RuntimeTools};
use supplyguard::security::injection::InjectionDetector;
use supplyguard::skills::license_check::LicensePolicy;

fn fixture(relative: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("fixtures")
        .join(relative)
}

fn policy() -> LicensePolicy {
    let text = std::fs::read_to_string(fixture("policies/license_policy.json")).expect("policy");
    serde_json::from_str(&text).expect("policy parses")
}

fn tools() -> (RuntimeTools, PathBuf) {
    let dir = tempfile::tempdir().expect("tempdir");
    let db_path = dir.path().join("audit.db");
    let chain = AuditChain::open(&db_path, b"orchestrator-test-key").expect("chain");
    let tools = RuntimeTools {
        registry: Arc::new(NpmLocal::new().expect("npm local")),
        vuln_source: Arc::new(OsvLocal::new().expect("osv local")),
        license_db: Arc::new(SpdxLocal::new().expect("spdx local")),
        audit_chain: Arc::new(chain),
        injection: InjectionDetector::with_builtin_rules().expect("detector"),
        license_policy: policy(),
    };
    (tools, dir.keep())
}

#[test]
fn scan_of_demo_app_blocks_the_hallucinated_dependency() {
    let (tools, _keep) = tools();
    let orchestrator = LocalOrchestrator::new(tools);
    let outcome = orchestrator
        .run_scan(&fixture("demo-app"), false)
        .expect("scan succeeds");

    assert_eq!(outcome.verdict, Verdict::Block);
    assert_eq!(outcome.risk_level, RiskLevel::Critical);
    assert!(outcome.seal.verified, "audit chain verifies after seal");

    // Reason ladder: hallucination dominates the demo-app signals.
    assert!(
        outcome
            .risk_profile
            .human_review_reasons
            .iter()
            .any(|reason| reason.contains("Hallucinated") || reason.contains("Prompt-injection"))
    );

    // Snapshot present in scan mode with the demo-app mix.
    let snapshot = outcome.snapshot.as_ref().expect("scan carries snapshot");
    assert_eq!(snapshot.packages.len(), 6);
}

#[test]
fn guard_allows_a_clean_upgrade_diff() {
    let (tools, _keep) = tools();
    let orchestrator = LocalOrchestrator::new(tools);
    let outcome = orchestrator
        .run_guard(
            SessionId::new("guard-clean"),
            EventSource::GitHubPr,
            "https://github.com/acme/demo-app".to_string(),
            "cafebabe".to_string(),
            vec![DependencyChange {
                package_name: "express".to_string(),
                old_version: Some("4.16.0".to_string()),
                new_version: Some("4.17.3".to_string()),
                is_new: false,
                ecosystem: "npm".to_string(),
                context_text: "upgrade express for CVE-2022-24999".to_string(),
            }],
        )
        .expect("guard runs");

    assert_eq!(outcome.verdict, Verdict::Allow);
    assert_eq!(outcome.risk_level, RiskLevel::Low);
    assert_eq!(
        outcome.strategy,
        supplyguard::models::messages::RemediationStrategy::CommentOnly
    );
    assert_eq!(
        outcome
            .remediation
            .artifacts
            .get("action_taken")
            .and_then(serde_json::Value::as_str),
        Some("no_action_required")
    );
}

#[test]
fn guard_blocks_a_new_hallucinated_package() {
    let (tools, _keep) = tools();
    let orchestrator = LocalOrchestrator::new(tools);
    let outcome = orchestrator
        .run_guard(
            SessionId::new("guard-lodos"),
            EventSource::GitHubPr,
            "https://github.com/acme/demo-app".to_string(),
            "deadbeef".to_string(),
            vec![DependencyChange {
                package_name: "lodos".to_string(),
                old_version: None,
                new_version: Some("^1.0.0".to_string()),
                is_new: true,
                ecosystem: "npm".to_string(),
                context_text: "import { cloneDeep } from 'lodos'; // generated by Copilot"
                    .to_string(),
            }],
        )
        .expect("guard runs");
    assert_eq!(outcome.verdict, Verdict::Block);
    assert_eq!(outcome.risk_level, RiskLevel::Critical);
    let comment = outcome
        .remediation
        .artifacts
        .get("comment_body")
        .and_then(serde_json::Value::as_str)
        .expect("blocking comment");
    assert!(comment.contains("blocked this dependency change"));
}

#[test]
fn guard_requires_human_review_for_a_high_cve() {
    let (tools, _keep) = tools();
    let orchestrator = LocalOrchestrator::new(tools);
    let outcome = orchestrator
        .run_guard(
            SessionId::new("guard-cve"),
            EventSource::GitHubPr,
            "https://github.com/acme/demo-app".to_string(),
            "deadbeef".to_string(),
            vec![DependencyChange {
                package_name: "lodash".to_string(),
                old_version: None,
                new_version: Some("4.17.15".to_string()),
                is_new: true,
                ecosystem: "npm".to_string(),
                context_text: "bump lodash".to_string(),
            }],
        )
        .expect("guard runs");
    assert_eq!(outcome.verdict, Verdict::RequireHumanReview);
    assert_eq!(outcome.risk_level, RiskLevel::High);
}

#[test]
fn events_fire_in_expected_order_and_states_traverse_linearly() {
    let (tools, _keep) = tools();
    let events: Arc<Mutex<Vec<OrchestratorEvent>>> = Arc::new(Mutex::new(Vec::new()));
    let sink_events = events.clone();
    let orchestrator = LocalOrchestrator::with_sink(
        tools,
        Arc::new(move |event: &OrchestratorEvent| {
            sink_events.lock().expect("sink lock").push(event.clone());
        }),
    );

    let outcome = orchestrator
        .run_guard(
            SessionId::new("guard-events"),
            EventSource::GitHubPr,
            "file:///demo".to_string(),
            "deadbeef".to_string(),
            vec![DependencyChange {
                package_name: "lodos".to_string(),
                old_version: None,
                new_version: Some("1.0.0".to_string()),
                is_new: true,
                ecosystem: "npm".to_string(),
                context_text: "suspicious".to_string(),
            }],
        )
        .expect("guard runs");

    let collected = events.lock().expect("lock");
    let names: Vec<String> = collected
        .iter()
        .map(|event| match event {
            OrchestratorEvent::ScanStarted { .. } => "started",
            OrchestratorEvent::ScanProgress { .. } => "progress",
            OrchestratorEvent::GuardVerdict { .. } => "verdict",
            OrchestratorEvent::AuditAppended { .. } => "audit",
            OrchestratorEvent::ScanCompleted { .. } => "completed",
        })
        .map(str::to_string)
        .collect();
    assert_eq!(names.first().map(String::as_str), Some("started"));
    assert_eq!(names.last().map(String::as_str), Some("completed"));
    assert!(names.iter().any(|name| name == "verdict"));
    assert_eq!(
        names.iter().filter(|name| *name == "audit").count(),
        2,
        "verdict + sealed audit events"
    );

    // Timeline: the full linear lifecycle in order.
    let states: Vec<SessionState> = outcome.timeline.iter().map(|(state, _)| *state).collect();
    assert_eq!(
        states,
        vec![
            SessionState::Received,
            SessionState::Analyzing,
            SessionState::Arbitrating,
            SessionState::Remediating,
            SessionState::Verifying,
            SessionState::Sealed,
        ]
    );

    // Session was recorded in the store.
    assert!(orchestrator.store().get("guard-events").is_some());
}

#[test]
fn corrupted_lockfile_scan_fails_conservatively() {
    let (tools, _keep) = tools();
    let orchestrator = LocalOrchestrator::new(tools);
    let result = orchestrator.run_scan(&fixture("lockfiles").join("..").join("lockfiles"), false);
    // Scan the corrupted fixture directory itself: no package-lock.json there
    // -> fatal invalid input (never a silent pass).
    assert!(result.is_err());
}

#[test]
fn outcome_json_never_carries_untrusted_markers_or_raw_context() {
    let (tools, _keep) = tools();
    let orchestrator = LocalOrchestrator::new(tools);
    let outcome = orchestrator
        .run_guard(
            SessionId::new("guard-raw"),
            EventSource::GitHubPr,
            "file:///demo".to_string(),
            "deadbeef".to_string(),
            vec![DependencyChange {
                package_name: "left-pad".to_string(),
                old_version: None,
                new_version: Some("1.3.0".to_string()),
                is_new: true,
                ecosystem: "npm".to_string(),
                context_text: "import x from 'raw-secret-context-marker';".to_string(),
            }],
        )
        .expect("guard runs");
    let json = serde_json::to_string(&outcome).expect("serialize");
    assert!(!json.contains("<untrusted_source>"));
    assert!(!json.contains("raw-secret-context-marker"));
}

#[test]
fn response_mode_finds_affected_packages_for_known_cve() {
    let (tools, _keep) = tools();
    let orchestrator = LocalOrchestrator::new(tools);
    let outcome = orchestrator
        .run_response("CVE-2020-8203", &fixture("demo-app"))
        .expect("response runs");

    assert_eq!(outcome.cve_id, "CVE-2020-8203");
    assert_eq!(outcome.affected_count, 1);
    assert_eq!(outcome.affected_packages[0].package_name, "lodash");
    assert_eq!(outcome.affected_packages[0].installed_version, "4.17.4");
    assert!(
        outcome.affected_packages[0]
            .cves
            .contains(&"CVE-2020-8203".to_string())
    );
    // Severity is the max across ALL advisories matching the package, not
    // just the queried CVE — lodash 4.17.4 also matches CVE-2019-10744 (critical).
    assert_eq!(outcome.affected_packages[0].severity, "critical");
    assert_eq!(outcome.verdict, Verdict::Block);
    assert_eq!(outcome.risk_level, RiskLevel::Critical);
    assert!(outcome.seal.verified, "audit chain verifies after seal");
    assert!(outcome.snapshot.is_some());
}

#[test]
fn response_mode_blocks_when_critical_cve_found() {
    let (tools, _keep) = tools();
    let orchestrator = LocalOrchestrator::new(tools);
    let outcome = orchestrator
        .run_response("CVE-2019-10744", &fixture("demo-app"))
        .expect("response runs");

    assert_eq!(outcome.affected_count, 1);
    assert_eq!(outcome.affected_packages[0].package_name, "lodash");
    assert_eq!(outcome.affected_packages[0].severity, "critical");
    assert_eq!(outcome.verdict, Verdict::Block);
    assert_eq!(outcome.risk_level, RiskLevel::Critical);
}

#[test]
fn response_mode_allows_when_no_packages_affected() {
    let (tools, _keep) = tools();
    let orchestrator = LocalOrchestrator::new(tools);
    let outcome = orchestrator
        .run_response("CVE-9999-9999", &fixture("demo-app"))
        .expect("response runs");

    assert_eq!(outcome.affected_count, 0);
    assert_eq!(outcome.affected_packages.len(), 0);
    assert_eq!(outcome.verdict, Verdict::Allow);
    assert_eq!(outcome.risk_level, RiskLevel::Safe);
    assert_eq!(outcome.total_scanned, 6);
}

#[test]
fn response_mode_events_follow_expected_order() {
    let (tools, _keep) = tools();
    let events: Arc<Mutex<Vec<OrchestratorEvent>>> = Arc::new(Mutex::new(Vec::new()));
    let sink_events = events.clone();
    let orchestrator = LocalOrchestrator::with_sink(
        tools,
        Arc::new(move |event: &OrchestratorEvent| {
            sink_events.lock().expect("sink lock").push(event.clone());
        }),
    );

    let outcome = orchestrator
        .run_response("CVE-2020-8203", &fixture("demo-app"))
        .expect("response runs");

    let collected = events.lock().expect("lock");
    let names: Vec<String> = collected
        .iter()
        .map(|event| match event {
            OrchestratorEvent::ScanStarted { .. } => "started",
            OrchestratorEvent::ScanProgress { .. } => "progress",
            OrchestratorEvent::GuardVerdict { .. } => "verdict",
            OrchestratorEvent::AuditAppended { .. } => "audit",
            OrchestratorEvent::ScanCompleted { .. } => "completed",
        })
        .map(str::to_string)
        .collect();
    assert_eq!(names.first().map(String::as_str), Some("started"));
    assert_eq!(names.last().map(String::as_str), Some("completed"));
    assert!(names.iter().any(|name| name == "verdict"));
    assert_eq!(
        names.iter().filter(|name| *name == "audit").count(),
        2,
        "verdict + sealed audit events"
    );

    // Timeline: full linear lifecycle.
    let states: Vec<SessionState> = outcome.timeline.iter().map(|(state, _)| *state).collect();
    assert_eq!(
        states,
        vec![
            SessionState::Received,
            SessionState::Analyzing,
            SessionState::Arbitrating,
            SessionState::Remediating,
            SessionState::Verifying,
            SessionState::Sealed,
        ]
    );
}
